name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - python-version: '3.11'
            architecture: x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --clean cleancli.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CleanCLI-Windows-x64
          path: dist/CleanCLI.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: CleanCLI-Windows-x64
          path: ./dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/CleanCLI.exe
          generate_release_notes: true
          draft: false
          prerelease: false
